graph TD
N0["(BLUE) AND (all of, in order) Comparative lit in English and German"]
N5["(RED) AND (all of, any order)"]
N0 -- itemListElement --> N5
N0["(BLUE) AND (all of, in order) Comparative lit in English and German"]
N1["(A) Intro to Lit"]
N0 -- itemListElement --> N1
N2["(GREEN) OR (any of)"]
N3["(B) English Lit by CA"]
N2 -- itemListElement --> N3
N5["(RED) AND (all of, any order)"]
N6["(D) German Lit"]
N5 -- itemListElement --> N6
N2["(GREEN) OR (any of)"]
N5["(RED) AND (all of, any order)"]
N2 -- nextItem --> N5
N5["(RED) AND (all of, any order)"]
N7["(E) Comparative Lit"]
N5 -- itemListElement --> N7
N2["(GREEN) OR (any of)"]
N4["(C) English Lit by GB"]
N2 -- itemListElement --> N4
N1["(A) Intro to Lit"]
N2["(GREEN) OR (any of)"]
N1 -- nextItem --> N2
N5["(RED) AND (all of, any order)"]
N8["(F) Compare German and English Lit"]
N5 -- nextItem --> N8
N0["(BLUE) AND (all of, in order) Comparative lit in English and German"]
N8["(F) Compare German and English Lit"]
N0 -- itemListElement --> N8
N0["(BLUE) AND (all of, in order) Comparative lit in English and German"]
N2["(GREEN) OR (any of)"]
N0 -- itemListElement --> N2
