graph TD
N1["Module: Python [Green]"]
N8["(GRa) Data Analysis and Representation in Python"]
N1 -- itemListElement --> N8
N1["Module: Python [Green]"]
N9["(GRb) Introduction to Machine Learning with Python"]
N1 -- itemListElement --> N9
N2["(G1) First Steps with Python in Life Sciences"]
N3["(G2a) Explore and Visualise Your Data with Python"]
N2 -- nextItem --> N3
N2["(G1) First Steps with Python in Life Sciences"]
N8["(GRa) Data Analysis and Representation in Python"]
N2 -- nextItem --> N8
N1["Module: Python [Green]"]
N5["(G2c) Interactive Visualisation with Python"]
N1 -- itemListElement --> N5
N2["(G1) First Steps with Python in Life Sciences"]
N5["(G2c) Interactive Visualisation with Python"]
N2 -- nextItem --> N5
N7["(R1) Introduction to Statistics and Data Visualisation with R"]
N8["(GRa) Data Analysis and Representation in Python"]
N7 -- nextItem --> N8
N7["(R1) Introduction to Statistics and Data Visualisation with R"]
N9["(GRb) Introduction to Machine Learning with Python"]
N7 -- nextItem --> N9
N1["Module: Python [Green]"]
N4["(G2b) Optimising Python Code for Better Performance"]
N1 -- itemListElement --> N4
N2["(G1) First Steps with Python in Life Sciences"]
N4["(G2b) Optimising Python Code for Better Performance"]
N2 -- nextItem --> N4
N1["Module: Python [Green]"]
N6["Module: Machine Learning [Red]"]
N1 -- nextItem --> N6
N6["Module: Machine Learning [Red]"]
N7["(R1) Introduction to Statistics and Data Visualisation with R"]
N6 -- itemListElement --> N7
N2["(G1) First Steps with Python in Life Sciences"]
N9["(GRb) Introduction to Machine Learning with Python"]
N2 -- nextItem --> N9
N1["Module: Python [Green]"]
N3["(G2a) Explore and Visualise Your Data with Python"]
N1 -- itemListElement --> N3
N1["Module: Python [Green]"]
N2["(G1) First Steps with Python in Life Sciences"]
N1 -- itemListElement --> N2
N6["Module: Machine Learning [Red]"]
N8["(GRa) Data Analysis and Representation in Python"]
N6 -- itemListElement --> N8
N6["Module: Machine Learning [Red]"]
N9["(GRb) Introduction to Machine Learning with Python"]
N6 -- itemListElement --> N9
