graph TD
N1["Module: Python [Green]"]
N5["(G2c) Interactive Visualisation with Python"]
N1 -- itemListElement --> N5
N1["Module: Python [Green]"]
N2["(G1) First Steps with Python in Life Sciences"]
N1 -- itemListElement --> N2
N2["(G1) First Steps with Python in Life Sciences"]
N2 -- nextItem --> TM_GRa
N7["(R1) Introduction to Statistics and Data Visualisation with R"]
N7 -- nextItem --> TM_GRa
N2["(G1) First Steps with Python in Life Sciences"]
N4["(G2b) Optimising Python Code for Better Performance"]
N2 -- nextItem --> N4
N1["Module: Python [Green]"]
N1 -- itemListElement --> TM_GRa
N1["Module: Python [Green]"]
N3["(G2a) Explore and Visualise Your Data with Python"]
N1 -- itemListElement --> N3
N6["Module: Machine Learning [Red]"]
N6 -- itemListElement --> TM_GRb
N7["(R1) Introduction to Statistics and Data Visualisation with R"]
N7 -- nextItem --> TM_GRb
N1["Module: Python [Green]"]
N6["Module: Machine Learning [Red]"]
N1 -- nextItem --> N6
N2["(G1) First Steps with Python in Life Sciences"]
N5["(G2c) Interactive Visualisation with Python"]
N2 -- nextItem --> N5
N6["Module: Machine Learning [Red]"]
N6 -- itemListElement --> TM_GRa
N2["(G1) First Steps with Python in Life Sciences"]
N3["(G2a) Explore and Visualise Your Data with Python"]
N2 -- nextItem --> N3
N1["Module: Python [Green]"]
N4["(G2b) Optimising Python Code for Better Performance"]
N1 -- itemListElement --> N4
N6["Module: Machine Learning [Red]"]
N7["(R1) Introduction to Statistics and Data Visualisation with R"]
N6 -- itemListElement --> N7
N2["(G1) First Steps with Python in Life Sciences"]
N2 -- nextItem --> TM_GRb
N1["Module: Python [Green]"]
N1 -- itemListElement --> TM_GRb
