graph TD
N6["(2.2) FAIR for busy biologists"]
N7["(2.3) RDMbites | FAIRification tools and templates"]
N6 -- nextItem --> N7
N0["Data Management for Researchers"]
N1["(TOPIC 1) Introduction to Data Management"]
N0 -- itemListElement --> N1
N9["(3.1) ESTONIA / Bring Your Own Data Management Plan"]
N10["(3.2) NBISweden/module-dmp-dm-practices"]
N9 -- nextItem --> N10
N7["(2.3) RDMbites | FAIRification tools and templates"]
N8["(TOPIC 3): (ONE OF) Data Management Plans"]
N7 -- nextItem --> N8
N4["(TOPIC 2): FAIR data"]
N7["(2.3) RDMbites | FAIRification tools and templates"]
N4 -- itemListElement --> N7
N1["(TOPIC 1) Introduction to Data Management"]
N3["(1.2) Crash Course In Data Management"]
N1 -- itemListElement --> N3
N2["(1.1) ELIXIR-CONVERGE - The why of research data management"]
N3["(1.2) Crash Course In Data Management"]
N2 -- nextItem --> N3
N8["(TOPIC 3): (ONE OF) Data Management Plans"]
N10["(3.2) NBISweden/module-dmp-dm-practices"]
N8 -- itemListElement --> N10
N4["(TOPIC 2): FAIR data"]
N8["(TOPIC 3): (ONE OF) Data Management Plans"]
N4 -- nextItem --> N8
N4["(TOPIC 2): FAIR data"]
N6["(2.2) FAIR for busy biologists"]
N4 -- itemListElement --> N6
N0["Data Management for Researchers"]
N4["(TOPIC 2): FAIR data"]
N0 -- itemListElement --> N4
N4["(TOPIC 2): FAIR data"]
N5["(2.1) FAIRsharing in a nutshell"]
N4 -- itemListElement --> N5
N1["(TOPIC 1) Introduction to Data Management"]
N2["(1.1) ELIXIR-CONVERGE - The why of research data management"]
N1 -- itemListElement --> N2
N0["Data Management for Researchers"]
N8["(TOPIC 3): (ONE OF) Data Management Plans"]
N0 -- itemListElement --> N8
N8["(TOPIC 3): (ONE OF) Data Management Plans"]
N9["(3.1) ESTONIA / Bring Your Own Data Management Plan"]
N8 -- itemListElement --> N9
N5["(2.1) FAIRsharing in a nutshell"]
N6["(2.2) FAIR for busy biologists"]
N5 -- nextItem --> N6
N1["(TOPIC 1) Introduction to Data Management"]
N4["(TOPIC 2): FAIR data"]
N1 -- nextItem --> N4
